### ISSUE TITLE
Create basic data structures with basic functions (CRUD)

### ISSUE THREAD

**Issue by DcodeZw3** [DcodeZw3/hacktober-javacodes1#9]
Try to implement a switch case based menu driven program
dont use datastructure packages (if any)

**Comment by GenDelta** [comment]
I would like to work on this issue.

**Comment by GenDelta** [comment]
I have added a menu driven Stack data structure program to resolve the given issue. Kindly check and approve the PR if you are content with the response.

**Comment by GenDelta** [comment]
I have added a similar menu driven Queue data structure code to help close the given issue.  Kindly check and approve the PR if you are content with the response.

**Comment by DcodeZw3** [comment]
try to commit to the issue.use the #9 issue number

**Comment by KaustubhBiswas** [comment]
I would like to commit to the the #9 issue.

**Comment by GenDelta** [comment]
Edited my commits to reference this issue. Now, kindly approve if you feel like the code is okay.
